# Generated by Django 5.2 on 2025-04-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('company', models.CharField(max_length=240, verbose_name='Company')),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(verbose_name='Requirements')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('location', models.CharField(max_length=240, verbose_name='Location')),
                ('employment_type', models.CharField(max_length=50, verbose_name='Employment Type')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='Posted Date')),
                ('url', models.URLField(max_length=512, verbose_name='Vacancy URL')),
            ],
        ),
    ]
