# Generated by Django 5.2.1 on 2025-06-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IamToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
    ]
